hr/urls.py
from django.urls import path

from .views import (
    hr_dashboard_view,
    hr_login_view,
    hr_logout_view,
    get_designation_json,
    
)

from .hrviews import employeecrud
from .hrviews import departmentcrud
from .hrviews import announcementcrud

app_name = 'hr'
urlpatterns = [
    path('', hr_dashboard_view, name='hr-home'),
    path('login/', hr_login_view, name='hr-login'),
    path('logout/', hr_logout_view, name='hr-logout'),
    path('designation/json/get/', get_designation_json, name='hr-get-designation'),
    
    path('employees/', employeecrud.HrEmployeeListView.as_view(), name='hr-employee-list'),
    path('employee/create/', employeecrud.create_employee_view, name='hr-employee-create'),
    path('employee/<pk>/change/', employeecrud.UpdateEmployeeView.as_view(), name='hr-employee-change'),
    path('employee/<pk>/password/', employeecrud.change_password_view, name="employee-change-password"),
    path('employee/<pk>/delete/', employeecrud.DeleteUserView.as_view(), name="employee-delete"),

    path('department/', departmentcrud.DeparmentListView.as_view(), name='hr-department-list'),
    path('department/add/', departmentcrud.create_department_view, name='hr-department-add'),
    path('department/<pk>/delete/', departmentcrud.DeleteDepartmentView.as_view(), name='hr-department-delete'),
    path('department/<pk>/change/', departmentcrud.update_department_view, name='hr-department-change'),

    path('announcements/', announcementcrud.AnnouncementView.as_view(), name='hr-announcement-list'),
    path('announcements/add/', announcementcrud.create_announcement_view, name='hr-announcement-add'),
    path('announcements/<pk>/delete/', announcementcrud.DeleteAnnouncementView.as_view(), name='hr-announcement-delete'),
    path('announcements/<pk>/change/', announcementcrud.UpdateAnnouncementView.as_view(), name='hr-announcement-change')

]

simplehrms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('hr/', include('hr.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hr/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from PIL import Image


class Department(models.Model):
    name = models.CharField(max_length = 50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Designation(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length = 50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class UserLevel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Profile(models.Model):
    MALE = 'Male'
    FEMALE = 'Female'
    GENDER =  (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    employee_id = models.CharField(max_length=20, blank=True, null=True, unique=True)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    nationality = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=6, choices=GENDER, default=MALE)
    date_of_birth = models.DateField(null=True, blank=True)
    religion = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    passport = models.CharField(max_length=50, blank=True, null=True)
    national_id = models.CharField(max_length=50, blank=True, null=True)
    mobile_number = models.CharField(max_length=50, blank=True, null=True)
    extension = models.IntegerField(blank=True, null=True)
    joining_date = models.DateField(null=True, blank=True)
    last_login = models.DateTimeField(null=True, blank=True)
    exit_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='avatar/', default='default.png', blank=True)
    designation = models.ForeignKey(Designation, on_delete=models.CASCADE, null=True, blank=True )
    salary = models.DecimalField(default=0, max_digits=19, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user_level = models.ForeignKey(UserLevel, on_delete=models.CASCADE, null=True, blank=True)
    personal_email = models.EmailField(null=True, blank=True)

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"
    

    def __str__(self):
        return '{} {}, {}'.format(self.user.first_name, self.user.last_name, self.middle_name,)
    
    def get_absolute_url(self):
        return reverse("employee:employee-detail", kwargs={"pk": self.user.pk})

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    # overriding the save method and resize image
    def save(self, *args, **kwargs):
        print("inside image manipulation")
        super().save(*args, **kwargs)

        img = Image.open(self.avatar.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)


class Leaves(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vacation = models.IntegerField(default=0)
    sick = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Leaves"
        verbose_name_plural = "Leaves"
    
    @receiver(post_save, sender=User)
    def create_user_leaves(sender, instance, created, **kwargs):
        if created:
            Leaves.objects.create(user=instance)


class BankAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    branch = models.CharField(max_length=100, blank=True, null=True)
    account = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    @receiver(post_save, sender=User)
    def create_user_bank_account(sender, instance, created, **kwargs):
        if created:
            BankAccount.objects.create(user=instance)
    
    # @receiver(post_save, sender=User)
    # def save_user_bank_account(sender, instance, **kwargs):
    #     # instance.bankaccount_set.save()
    #     print(instance.bankaccount_set.name)


class Announcement(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

hr/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField
from django.utils.safestring import mark_safe

# from string import Template
# from django.forms import ImageField

from .models import Profile, Department, UserLevel, BankAccount, Designation, Leaves


class UserForm(UserCreationForm):
    email = forms.EmailField(
        required=False,
        widget=forms.TextInput(attrs={'type':'email','class':'validate'}),
        help_text=mark_safe('<span class="helper-text" data-error="Wrong email format" data-success="Correct email format">Please enter valid email</span>')
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class ChangeUserForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ChangeUserPassword(forms.Form):
    password1 = forms.CharField(label='New password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='New password confirmation', widget=forms.PasswordInput())
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ChangeUserPassword, self).__init__(*args, **kwargs)
    
    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password_length = 8
        if len(password1) < password_length:
            raise forms.ValidationError("Password must be longer than {} characters".format(password_length))
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError("The two password fields didn't match.")
    
    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['password2'])
        if commit:
            self.user.save()
        return self.user


# class PictureWidget(forms.widgets.Widget):
#     def render(self, name, value, attrs=None):
#         html =  Template("""<img src='$link'/> """)
#         return mark_safe(html.substitute(link=value))


class ProfileForm(forms.ModelForm):
    EMPTY_CHOICES = [('','---------')]
    GENDER_CHOICES = [('Male','Male'), ('Female','Female')]

    date_of_birth = forms.DateField(help_text='Format: YYYY-MM-DD', required=False, widget=forms.TextInput(attrs={'class':'datepicker'}))
    avatar=forms.ImageField(help_text='Dimension must be 300x300 px', required=False, widget = forms.FileInput(attrs = {'onchange' : "readURL(this);"}))
    # avatar=forms.ImageField()
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=False, widget=forms.Select(attrs={'class':'myselect'}))
    department = forms.ModelChoiceField(queryset=Department.objects.all(), widget=forms.Select(attrs={'class':'myselect'}),required=False)
    designation = forms.ModelChoiceField(queryset=Designation.objects.all(), required=False, widget=forms.Select(attrs={'class':'myselect'}))
    user_level = forms.ModelChoiceField(queryset=UserLevel.objects.all(),  widget=forms.Select(attrs={'class':'myselect'}),required=False)
    is_admin = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class':'filled-in'}))
    extension = forms.IntegerField(label="Extension Number", required=False, widget=forms.TextInput(attrs={'type':'number'}))
    personal_email = forms.EmailField(
        required=False,
        widget=forms.TextInput(attrs={'type':'email','class':'validate'}),
        help_text=mark_safe('<span class="helper-text" data-error="Wrong email format" data-success="Correct email format">Please enter valid email</span>')
    )
    joining_date = forms.DateField(help_text='Format: YYYY-MM-DD', required=False, widget=forms.TextInput(attrs={'class':'datepicker'}))
    vacation = forms.IntegerField(help_text='Number of days', label="Vacation leave", required=False, widget=forms.TextInput(attrs={'type':'number'}))
    sick = forms.IntegerField(help_text='Number of days', label="Sick leave", required=False, widget=forms.TextInput(attrs={'type':'number'}))

    class Meta:
        model = Profile
        exclude = ['user']


class BankForm(forms.ModelForm):
    class Meta:
        model = BankAccount
        fields = ['name', 'branch', 'account']


class LeaveForm(forms.ModelForm):
    class Meta:
        model = Leaves
        exclude = ['user']

hr/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from django.urls import reverse_lazy

from datetime import datetime

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

from django.db.models.functions import Extract


from .decorators import admin_required

from .models import (
    Department,
    Profile,
)


@login_required(login_url=reverse_lazy('hr:hr-login'))
@admin_required
def hr_dashboard_view(request):
    # if not request.user.profile.is_admin:
    #     return redirect('employee:index')

    now = datetime.now()
    employees = User.objects.all()
    employeesCount = employees.count()
    departmentCount = Department.objects.all().count()

    thismonthbday = Profile.objects.annotate(
        birth_date_month = Extract('date_of_birth', 'month'),
        birth_date_day = Extract('date_of_birth', 'day')
        ).order_by('birth_date_month', 'birth_date_day').filter(
        date_of_birth__month = now.month, date_of_birth__day__gte=now.day)

    bdaytoday = thismonthbday.filter(date_of_birth__day = now.day)

    context = {
        'employeesCount':employeesCount,
        'departmentCount':departmentCount,
        'homeactive': 'active',
        'thismonthbday': thismonthbday,
        'bdaytoday' : bdaytoday,
        'currentmonth' : now
    }
    return render(request, 'hr/hr_home.html', context)


@login_required(login_url=reverse_lazy('hr:hr-login'))
@admin_required
def get_designation_json(request):
    deptid =  request.GET['deptID']
    
    deptarment = Department.objects.get(pk=deptid)
    designation_list = deptarment.designation_set.all().values('id', 'name')
    dl = list(designation_list)
    # print(designation_list)
    return JsonResponse(dl, safe=False)


def hr_login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()

            if user.profile.is_admin:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('hr:hr-home')

    else:
        form = AuthenticationForm()
    return render(request, 'hr/hr_login.html', {'form': form})


def hr_logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('hr:hr-login')
    else:
        # redundant fix this soon
        logout(request)
        return redirect('hr:hr-login')

hr/templates/hr/announcement_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Announcements
{% endblock title %}

{% block css %}
  <style>
    .status{
      padding:3px 9px;
    }
  </style>
{% endblock css %}

{% block content %}
<div id="mainbox">
  {% if messages %}
      {% for message in messages %}
      <div class="alert light-green lighten-3 green-text text-darken-4">
          <i class="warning material-icons left">warning</i>
          <span class="title">{{ message }}</span>
          <i class="close right green-text text-darken-4 material-icons">close</i>
      </div>
      {% endfor %}
  {% endif %}

    <div class="mycontainer mb27">
      <div class="nav-wrapper">
        <div class="col s12">
        <a href="{% url 'hr:hr-home' %}" class="breadcrumb">Home</a>
        <a href="{% url 'hr:hr-announcement-list' %}" class="breadcrumb">Announcements</a>
        </div>
      </div>
  </div>

  <div class="fixed-action-btn addbtn">
    <a href="{% url 'hr:hr-announcement-add' %}" class="btn-floating btn-large waves-effect waves-light cyan"><i class="material-icons">add</i></a>
  </div>

  <div class="container">
    <div class="card">
      <div class="card-content">
       
        <table class="highlight responsive-table" id="dept-table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {% for obj in annolist  %}
            <tr>
              <td class="valignko"><h6>{{ obj.title }}</h6></td>
              <td>{{ obj.start_date }}</td>
              <td>{{ obj.end_date }}</td>
              <td>
              {% if obj.status == 'active' %}
                  <span class="status green lighten-2 white-text">{{ obj.status|title }}</span>
              {% else %}
                  <span class="status red lighten-2 white-text">{{ obj.status|title }}</span>
              {% endif %}
              </td>
              <td class="valignko">
                <a href="{% url 'hr:hr-announcement-change' obj.pk %}" class="tooltipped black-text" data-position="top" data-tooltip="Edit"><i class="material-icons blue-grey-text">edit</i></a> &nbsp;

                <a href="{% url 'hr:hr-announcement-delete' obj.pk %}" class="tooltipped black-text" data-position="top" data-tooltip="Delete"><i class="material-icons red-text text-darken-2">delete</i></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    {% if annolist.has_other_pages %}

    {% if annolist.has_previous %}
    <a href="?page=1" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">First</a>
    <a href="?page={{ annolist.previous_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Previous</a>
    {% endif %}

    {% for num in annolist.paginator.page_range %}
    {% if annolist.number == num %}
      <a href="?page={{ num }}" class="btn-small light-blue">{{num}}</a>
    {% elif num > annolist.number|add:'-3' and num < annolist.number|add:'3'%}
      <a href="?page={{ num }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">{{num}}</a>
    {% endif %}
    {% endfor %}

    {% if annolist.has_next %}
    <a href="?page={{ annolist.next_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Next</a>
    <a href="?page={{ annolist.paginator.num_pages }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Last</a>
    {% endif %}

    {% endif %}
  
  </div>

</div><!-- mainbox -->
{% endblock content %}

hr/templates/hr/change_password_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Change Employee Password
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'hr/css/hr-employee-change.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet"  href="{% static 'hr/css/material_green.css' %}">
{% endblock css %}

{% block content %}
<div id="mainbox">
  <div class="mycontainer">
    <div class="nav-wrapper">
      <div class="col s12">
      <a href="{% url 'hr:hr-home' %}" class="breadcrumb">Home</a>
      <a href="{% url 'hr:hr-employee-list' %}" class="breadcrumb">Employees</a>
      <a href="{% url 'hr:hr-employee-change' userid %}" class="breadcrumb">Change</a>
      <a href="{% url 'hr:employee-change-password' userid %}" class="breadcrumb">Password</a>
      </div>
    </div>
    <h4>Change employee password</h4>
    <form method="POST">
        {% csrf_token %}
      <div class="row">
        
        <div class="col s12 m12 l12">
          <div class="card-panel">
            <div class="row no-mb">
              
              <div class="col s6">
                <div class="input-field">
                  <i class="material-icons prefix">lock</i>
                  {{ password_form.password1.label_tag }}
                  {{password_form.password1}}
                  {{ password_form.password1.errors }}
                  {% if password_form.password1.help_text %}
                    <small class="grey-text text-darken-2">{{ password_form.password1.help_text }}</small>
                  {% endif %}
                </div>
              </div>
              <div class="col s6">
                <div class="input-field">
                  <i class="material-icons prefix">lock</i>
                  {{ password_form.password2.label_tag }}
                  {{password_form.password2}}
                  {{ password_form.password2.errors }}
                  {% if password_form.password2.help_text %}
                    <small class="grey-text text-darken-2">{{ password_form.password2.help_text }}</small>
                  {% endif %}
                </div>
              </div>
              <div class="col">
              {{ password_form.non_field_errors }}
              <br>
              </div>
              <div class="col s12 m12 l12">
                <button class="btn btn-large waves-effect waves-light cyan" type="submit">Save changes<i class="material-icons right">send</i></button>
              </div>

            </div>
          </div> <!-- //card-panel -->
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

hr/templates/hr/department_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Deparments
{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
<div id="mainbox">
  {% if messages %}
      {% for message in messages %}
      <div class="alert light-green lighten-3 green-text text-darken-4">
          <i class="warning material-icons left">warning</i>
          <span class="title">{{ message }}</span>
          <i class="close right green-text text-darken-4 material-icons">close</i>
      </div>
      {% endfor %}
  {% endif %}

    <div class="mycontainer mb27">
      <div class="nav-wrapper">
        <div class="col s12">
        <a href="{% url 'hr:hr-home' %}" class="breadcrumb">Home</a>
        <a href="{% url 'hr:hr-department-list' %}" class="breadcrumb">Department</a>
        </div>
      </div>
  </div>

  <div class="fixed-action-btn addbtn">
    <a href="{% url 'hr:hr-department-add' %}" class="btn-floating btn-large waves-effect waves-light cyan"><i class="material-icons">add</i></a>
  </div>

  <div class="container">
    <div class="card">
      <div class="card-content">
        <table class="highlight responsive-table" id="dept-table">
          <thead>
            <tr>
              <th>Department</th>
              <th>Designation</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          {% for dept in object_list  %}
            <tr>
              <td class="valignko"><h6>{{ dept }}</h6></td>
              <td class="valignko">
                <ul>
                {% for desig in dept.designation_set.all  %}
                  <li>{{desig}}</li>
                {% endfor %}
                </ul>
              </td>
              <td class="valignko">
                <a href="{% url 'hr:hr-department-change' dept.id %}" class="tooltipped black-text" data-position="top" data-tooltip="Edit"><i class="material-icons blue-grey-text">edit</i></a> &nbsp;

                <a href="{% url 'hr:hr-department-delete' dept.id %}" class="tooltipped black-text" data-position="top" data-tooltip="Delete"><i class="material-icons red-text text-darken-2">delete</i></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    {% if is_paginated %}

    {% if page_obj.has_previous %}
    <a href="?page=1" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">First</a>
    <a href="?page={{ page_obj.previous_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a href="?page={{ num }}" class="btn-small light-blue">{{num}}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
      <a href="?page={{ num }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">{{num}}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Last</a>
    {% endif %}

    {% endif %}
  </div>

</div><!-- mainbox -->
{% endblock content %}

hr/templates/hr/profile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Employee List
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'hr/css/hr-employee-list.css' %}">
{% endblock css %}

{% block content %}
    
<div id="mainbox">
    {% if messages %}
        {% for message in messages %}
        <div class="alert light-green lighten-3 green-text text-darken-4">
            <i class="warning material-icons left">warning</i>
            <span class="title">{{ message }}</span>
            <i class="close right green-text text-darken-4 material-icons">close</i>
        </div>
        {% endfor %}
    {% endif %}

    <div class="mycontainer mb27">
        <div class="nav-wrapper">
            <div class="col s12">
            <a href="{% url 'hr:hr-home' %}" class="breadcrumb">Home</a>
            <a href="{% url 'hr:hr-employee-list' %}" class="breadcrumb">Employees</a>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn addbtn">
        <a href="{% url 'hr:hr-employee-create' %}" class="btn-floating btn-large waves-effect waves-light cyan"><i class="material-icons">add</i></a>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-content">
                <table class="highlight responsive-table">
                    <thead>
                        <tr>
                            <th>Employee ID</th>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Department</th>
                            <th>Designation</th>
                            <th>Active</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in object_list %}
                        <tr>
                            <td width="10%">{{ employee.employee_id }}</td>
                            <td class="avatar" width="20%"><img src="{{employee.avatar.url}}" alt="" height="100" width="100" class="circle"></td>
                            <td>{{ employee.user.get_full_name }}</td>
                            <td>{{ employee.designation.department }}</td>
                            <td>{{ employee.designation }}</td>
                            <td>
                                {% if employee.user.is_active %}
                                    <span class="status green lighten-2 white-text">{{ employee.user.is_active }}</span>
                                    {% else %}
                                    <span class="status red lighten-2 white-text">{{ employee.user.is_active }}</span>
                                {% endif %}
                            </td>
                            <td>
                                <div class="actions-box">
                                    <a href="{% url 'hr:hr-employee-change' employee.user.id %}" class="tooltipped" data-position="top" data-tooltip="Edit"><i class="material-icons blue-grey-text">edit</i></a> &nbsp;

                                    {% if not employee.user.is_superuser %}
                                    <a href="{% url 'hr:employee-delete' employee.user.id %}" class="tooltipped" data-position="top" data-tooltip="Delete"><i class="material-icons red-text text-darken-2">delete</i></a>
                                    {% endif %}

                                </div>
                            </td>
                            {% endfor %}
                        </tr>                    
                    </tbody>
                </table>
            </div>
        </div>
        
    {% if is_paginated %}
  
    {% if page_obj.has_previous %}
    <a href="?page=1" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">First</a>
    <a href="?page={{ page_obj.previous_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a href="?page={{ num }}" class="btn-small light-blue">{{num}}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
      <a href="?page={{ num }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">{{num}}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn-small light-blue lighten-5 blue-grey-text darken-text-1">Last</a>
    {% endif %}

    {% endif %}

    </div>
</div>
{% endblock content %}