employee/urls.py
from django.urls import path

from employee.views import (
  index_view,
  emp_login_view,
  home_view,
  emp_logout_view,
  PersonalDetailView,
  CompanyDetailView,
  )

app_name = 'employee'
urlpatterns = [
    path('', index_view, name='index'),
    path('dashboard/', home_view, name='home'),
    path('dashboard/login/', emp_login_view, name='login'),
    path('dashboard/logout/', emp_logout_view, name='logout'),
    path('dashboard/<pk>/personal-detail/', PersonalDetailView.as_view(), name='personal-detail'),
    path('dashboard/<pk>/company-detail/', CompanyDetailView.as_view(), name='company-detail'),

]

hr/urls.py
from django.urls import path

from .views import (
    hr_dashboard_view,
    hr_login_view,
    hr_logout_view,
    get_designation_json,
    
)

from .hrviews import employeecrud
from .hrviews import departmentcrud
from .hrviews import announcementcrud

app_name = 'hr'
urlpatterns = [
    path('', hr_dashboard_view, name='hr-home'),
    path('login/', hr_login_view, name='hr-login'),
    path('logout/', hr_logout_view, name='hr-logout'),
    path('designation/json/get/', get_designation_json, name='hr-get-designation'),
    
    path('employees/', employeecrud.HrEmployeeListView.as_view(), name='hr-employee-list'),
    path('employee/create/', employeecrud.create_employee_view, name='hr-employee-create'),
    path('employee/<pk>/change/', employeecrud.UpdateEmployeeView.as_view(), name='hr-employee-change'),
    path('employee/<pk>/password/', employeecrud.change_password_view, name="employee-change-password"),
    path('employee/<pk>/delete/', employeecrud.DeleteUserView.as_view(), name="employee-delete"),

    path('department/', departmentcrud.DeparmentListView.as_view(), name='hr-department-list'),
    path('department/add/', departmentcrud.create_department_view, name='hr-department-add'),
    path('department/<pk>/delete/', departmentcrud.DeleteDepartmentView.as_view(), name='hr-department-delete'),
    path('department/<pk>/change/', departmentcrud.update_department_view, name='hr-department-change'),

    path('announcements/', announcementcrud.AnnouncementView.as_view(), name='hr-announcement-list'),
    path('announcements/add/', announcementcrud.create_announcement_view, name='hr-announcement-add'),
    path('announcements/<pk>/delete/', announcementcrud.DeleteAnnouncementView.as_view(), name='hr-announcement-delete'),
    path('announcements/<pk>/change/', announcementcrud.UpdateAnnouncementView.as_view(), name='hr-announcement-change')

]

simplehrms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('hr/', include('hr.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.

employee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from datetime import datetime

from hr.models import Leaves, Announcement, BankAccount

from django.views.generic import (
    DetailView,
    # ListView,
    # UpdateView,
    # DeleteView,
)

@login_required(login_url=reverse_lazy('employee:login'))
def index_view(request):
  return redirect('employee:home')


@login_required(login_url=reverse_lazy('employee:login'))
def home_view(request):

  now = datetime.date(datetime.now())
  annoucements = Announcement.objects.filter(start_date__lte = now, end_date__gte=now).order_by('-pk')
  leaves = Leaves.objects.get(user=request.user)
  
  context = {
    'theemp':request.user,
    'leaves' : leaves,
    'annoucements':annoucements
  }
  return render(request, 'employee/emp_home.html', context)


@method_decorator([login_required(login_url=reverse_lazy('employee:login'))], name='dispatch')
class PersonalDetailView(DetailView):
  model = User
  template_name = 'employee/emp_personal_detail.html'

  def get_context_data(self, **kwargs):
      context = super(PersonalDetailView, self).get_context_data(**kwargs)
      theuser = User.objects.get(pk=self.kwargs["pk"])
      bank = BankAccount.objects.get(user=theuser)

      context['theemp'] = theuser
      context['bank'] = bank

      return context


@method_decorator([login_required(login_url=reverse_lazy('employee:login'))], name='dispatch')
class CompanyDetailView(DetailView):
  model = User
  template_name = 'employee/emp_company_detail.html'

  def get_context_data(self, **kwargs):
      context = super(CompanyDetailView, self).get_context_data(**kwargs)
      theuser = User.objects.get(pk=self.kwargs["pk"])

      context['theemp'] = theuser

      return context


def emp_login_view(request):
  if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    
    if form.is_valid():
      user = form.get_user()

      if user.is_active:
        login(request, user)
        
        if 'next' in request.POST:
          return redirect(request.POST.get('next'))
        else:
          return redirect('employee:home')
  else:
    form = AuthenticationForm()
  return render(request, 'employee/emp_login.html', {'form': form})


def emp_logout_view(request):
  logout(request)
  return redirect("employee:login")

employee/templates/employee/emp_company_detail.html
{% extends "base-emp.html" %}
{% load static %}

{% block title %}
Employee Company Details
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'employee/css/emp-avatarpanel.css' %}">
<link rel="stylesheet"  href="{% static 'employee/css/emp-company.css' %}">
{% endblock css %}

{% block content %}
<div class="section mycontainer">
  <div class="nav-wrapper mb27">
    <div class="col s12">
      <a href="{% url 'employee:home' %}" class="breadcrumb">Home</a>
      <a href="{% url 'employee:company-detail' theemp.pk %}" class="breadcrumb">Company Details</a>
    </div>
  </div>

  <div class="row">
    <!-- Col 1 -->
    {% include "employee/includes/_emp_col1.html" %}
    <!-- //Col 1 -->
    
    <!-- Col 2 -->
    <div class="col l6 m6 s12">
      <div class="card company-detail">
          <div class="card-title white-text cyan darken-1">
            Company Details
          </div>
        <div class="card-content">
          <p><b>DESIGNATION:</b> {{theemp.profile.designation}}</p>
          <p><b>DEPARTMENT:</b> {{theemp.profile.designation.department}}</p>
          <p><b>EXTENSION:</b> {{theemp.profile.extension}}</p>
          <p><b>EMAIL:</b> {{theemp.email}}</p>
          <p><b>SALARY:</b> {{theemp.profile.salary}}</p>
          <p><b>USER LEVEL:</b> {{theemp.profile.user_level}}</p>
          <p><b>IS ADMIN:</b> {{theemp.profile.is_admin}}</p>
        </div>
      </div>
    </div>
    <!-- //Col 2 -->

  </div>
</div>
{% endblock content %}

employee/templates/employee/emp_home.html
{% extends "base-emp.html" %}
{% load static %}

{% block title %}
Employee Dashboard
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'employee/css/emp-avatarpanel.css' %}">
<link rel="stylesheet"  href="{% static 'employee/css/emp-home.css' %}">
{% endblock css %}

{% block content %}
<div class="section mycontainer">
  <div class="row">
    <!-- Col 1 -->
    {% include "employee/includes/_emp_col1.html" %}
    <!-- //Col 1 -->

    <!-- Col 2 -->
    <div class="col l3 m6 s12">
      <div class="card personal-detail">
          <div class="card-title white-text teal ">
            Personal Details
          </div>
        <div class="card-content">
          <p><b>FIRST NAME:</b> {{theemp.first_name}}</p>
          <p><b>LAST NAME:</b> {{theemp.last_name}}</p>
          <p><b>MIDDLE NAME:</b> {{theemp.profile.middle_name}}</p>
          <p><b>PERSONAL EMAIL:</b> {{theemp.profile.personal_email}}</p>
          <p><b>MOBILE NUMBER:</b> {{theemp.profile.mobile_number}}</p>

        </div>
        <div class="card-action ">
          <a href="{% url "employee:personal-detail" theemp.pk %}">View More</a>
        </div>
      </div>

      <div class="card company-detail">
          <div class="card-title white-text cyan darken-1">
            Company Details
          </div>
        <div class="card-content">
          <p><b>DESIGNATION:</b> {{theemp.profile.designation}}</p>
          <p><b>DEPARTMENT:</b> {{theemp.profile.designation.department}}</p>
          <p><b>EXTENSION:</b> {{theemp.profile.extension}}</p>
          <p><b>EMAIL:</b> {{theemp.email}}</p>
        </div>
        <div class="card-action">
          <a href="{% url "employee:company-detail" theemp.pk %}">View More</a>
        </div>
      </div>
    </div>
    <!-- //Col 2 -->
    <div class="col l3 m6 s12">
      <div class="card leave-card">
        <div class="card-image">
          <img src="{% static 'img/vl-banner-2.jpg' %}" alt="">
        </div>
        <div class="card-content">
          <table class="centered">
            <thead>
              <tr>
                  <th>Given</th>
                  <th>Spend</th>
                  <th>Available</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td><h5>{{leaves.vacation}}</h5></td>
                <td><h5>0</h5></td>
                <td><h5>{{leaves.vacation}}</h5></td>
              </tr>
              <tr style="border-bottom:0px;">
                <td>Days</td>
                <td>Days</td>
                <td>Days</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="card-action grey lighten-3">
          <div class="row" style="margin-bottom:0px;">
            <div class="col l6 m6 s12 center">
              <a href="#">Apply for leave</a>
            </div>
            <div class="col l6 m6 s12 center">
              <a href="#" class="right">View all</a>
            </div>
          </div>
        </div>
      </div>

      <div class="card leave-card">
        <div class="card-image">
          <img src="{% static 'img/sl-banner.jpg' %}" alt="">
        </div>
        <div class="card-content">
          <table class="centered">
            <thead>
              <tr>
                  <th>Given</th>
                  <th>Spend</th>
                  <th>Available</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td><h5>{{leaves.sick}}</h5></td>
                <td><h5>0</h5></td>
                <td><h5>{{leaves.sick}}</h5></td>
              </tr>
              <tr style="border-bottom:0px;">
                <td>Days</td>
                <td>Days</td>
                <td>Days</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="card-action grey lighten-3">
          <div class="row" style="margin-bottom:0px;">
            <div class="col l6 m6 s12 center">
              <a href="#">Apply for leave</a>
            </div>
            <div class="col l6 m6 s12 center">
              <a href="#" class="right">View all</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="col l4 m6 s12">
      <!-- Announcement -->
      <div class="card">
        <ul class="collection with-header anno-collection">
          <li class="collection-header grey lighten-4"><h5>Announcements</h5></li>
          {% if annoucements %}
            {% for anno in annoucements %}
            <li class="collection-item">
              <h6><b>{{anno.title}}</b></h6>
              <p>{{anno.note|truncatewords:7}}</p>
              <button data-target="#modal{{anno.pk}}" class="right btn-small white red-text modal-trigger z-depth-0">Read more</button>
              <div class="alis"></div>
              <!-- Modal Structure -->
              <div id="#modal{{anno.pk}}" class="modal">
                <div class="modal-content">
                  <h4>{{anno.title}}</h4>
                  <p>{{anno.note}}</p>
                </div>
                <div class="modal-footer">
                  <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                </div>
              </div>
            </li>
            {% endfor %}
          {% else %}
            <li class="collection-item center">
              No Announcement
            </li>
          {% endif %}
        </ul>
      </div>

      <!-- Request -->
      <div class="card">
        <ul class="collection with-header">
          <li class="collection-header grey lighten-4"><h5>Your Requests</h5></li>
          <li class="center"><p>No Requests</p></li>
        </ul>
      </div>

    </div>
  </div>
</div>
{% endblock content %}
{% block jscontent %}
<script>
$(document).ready(function(){
    $('.modal').modal();
  });
</script>
{% endblock jscontent %}

employee/templates/employee/emp_login.html
{% extends 'login-base.html' %}
{% load static %}

{% block title %}
HR Login
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'employee/css/login.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
  <center>
  <div class="row mt90">
      <div class="col s12 m6 offset-m3">
        <div class="card ">
          <form method="POST">
            <div class="card-content">
              <img src="{% static 'img/simplehrms-cyan.jpg' %}" class="responsive-img">
              <br><br>
              <!-- <span class="card-title"><b>HR Login</b></span> -->
                {% csrf_token %}
                {% if form.errors %}
                    <p class="red-text">Please enter a correct username and password. Note that both fields may be case-sensitive.</p>
                {% endif %}
                {% for field in form %}
                    <div class="input-field">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.help_text %}
                    <small class="grey-text">{{ field.help_text }}</small>
                    {% endif %}
                    </div>
                {% endfor %}
                
                {% if request.GET.next %}
                <input type="hidden" name="next" value={{request.GET.next}}>
                {% endif %}
            </div>
            <div class="card-action">
                <button type="submit" class="btn btn-large waves-effect cyan darken-1">Login</button>
            </div>
            </form>
        </div>
      </div>
    </div>
  </center>
    
</div>
{% endblock content %}

employee/templates/employee/emp_personal_detail.html
{% extends "base-emp.html" %}
{% load static %}

{% block title %}
Employee Personal Details
{% endblock title %}

{% block css %}
<link rel="stylesheet"  href="{% static 'employee/css/emp-avatarpanel.css' %}">
<link rel="stylesheet"  href="{% static 'employee/css/emp-personal.css' %}">
{% endblock css %}

{% block content %}
<div class="section mycontainer">
  <div class="nav-wrapper mb27">
    <div class="col s12">
      <a href="{% url 'employee:home' %}" class="breadcrumb">Home</a>
      <a href="{% url 'employee:personal-detail' theemp.pk %}" class="breadcrumb">Personal Details</a>
    </div>
  </div>

  <div class="row">
    <!-- Col 1 -->
    {% include "employee/includes/_emp_col1.html" %}
    <!-- //Col 1 -->
    
    <!-- Col 2 -->
    <div class="col l6 m6 s12">
      <div class="card personal-detail">
          <div class="card-title white-text teal ">
            Personal Details
          </div>
        <div class="card-content">
          <p><b>FIRST NAME:</b> {{theemp.first_name}}</p>
          <p><b>LAST NAME:</b> {{theemp.last_name}}</p>
          <p><b>MIDDLE NAME:</b> {{theemp.profile.middle_name}}</p>
          <p><b>GENDER:</b> {{theemp.profile.gender}}</p>
          <p><b>PERSONAL EMAIL:</b> {{theemp.profile.personal_email}}</p>
          <p><b>MOBILE NUMBER:</b> {{theemp.profile.mobile_number}}</p>
          <p><b>NATIONALITY:</b> {{theemp.profile.nationality}}</p>
          <p><b>BIRTHDAY:</b> {{theemp.profile.date_of_birth}}</p>
          <p><b>RELIGION:</b> {{theemp.profile.religion}}</p>
          <p><b>ADDRESS:</b> {{theemp.profile.address}}</p>
          <p><b>NATIONAL ID:</b> {{theemp.profile.national_id}}</p>
          <p><b>PASSPORT:</b> {{theemp.profile.passport}}</p>
        </div>

      </div>
    </div>
    <!-- //Col 2 -->

    <!-- Col 3 -->
    <div class="col l4 m6 s12">
      <div class="card personal-detail">
          <div class="card-title white-text teal">
            Bank Details
          </div>
        <div class="card-content">
          <p><b>BANK NAME:</b> {{bank.name}}</p>
          <p><b>ACCOUNT:</b> {{bank.account}}</p>
          <p><b>BRANCH:</b> {{bank.branch}}</p>
        </div>

      </div>
    </div>
    <!-- //Col 3 -->
  
  </div>
</div>
{% endblock content %}