employee/urls.py
from django.urls import path

from employee.views import (
  index_view,
  emp_login_view,
  home_view,
  emp_logout_view,
  PersonalDetailView,
  CompanyDetailView,
  )

app_name = 'employee'
urlpatterns = [
    path('', index_view, name='index'),
    path('dashboard/', home_view, name='home'),
    path('dashboard/login/', emp_login_view, name='login'),
    path('dashboard/logout/', emp_logout_view, name='logout'),
    path('dashboard/<pk>/personal-detail/', PersonalDetailView.as_view(), name='personal-detail'),
    path('dashboard/<pk>/company-detail/', CompanyDetailView.as_view(), name='company-detail'),

]

hr/urls.py
from django.urls import path

from .views import (
    hr_dashboard_view,
    hr_login_view,
    hr_logout_view,
    get_designation_json,
    
)

from .hrviews import employeecrud
from .hrviews import departmentcrud
from .hrviews import announcementcrud

app_name = 'hr'
urlpatterns = [
    path('', hr_dashboard_view, name='hr-home'),
    path('login/', hr_login_view, name='hr-login'),
    path('logout/', hr_logout_view, name='hr-logout'),
    path('designation/json/get/', get_designation_json, name='hr-get-designation'),
    
    path('employees/', employeecrud.HrEmployeeListView.as_view(), name='hr-employee-list'),
    path('employee/create/', employeecrud.create_employee_view, name='hr-employee-create'),
    path('employee/<pk>/change/', employeecrud.UpdateEmployeeView.as_view(), name='hr-employee-change'),
    path('employee/<pk>/password/', employeecrud.change_password_view, name="employee-change-password"),
    path('employee/<pk>/delete/', employeecrud.DeleteUserView.as_view(), name="employee-delete"),

    path('department/', departmentcrud.DeparmentListView.as_view(), name='hr-department-list'),
    path('department/add/', departmentcrud.create_department_view, name='hr-department-add'),
    path('department/<pk>/delete/', departmentcrud.DeleteDepartmentView.as_view(), name='hr-department-delete'),
    path('department/<pk>/change/', departmentcrud.update_department_view, name='hr-department-change'),

    path('announcements/', announcementcrud.AnnouncementView.as_view(), name='hr-announcement-list'),
    path('announcements/add/', announcementcrud.create_announcement_view, name='hr-announcement-add'),
    path('announcements/<pk>/delete/', announcementcrud.DeleteAnnouncementView.as_view(), name='hr-announcement-delete'),
    path('announcements/<pk>/change/', announcementcrud.UpdateAnnouncementView.as_view(), name='hr-announcement-change')

]

simplehrms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('hr/', include('hr.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.

employee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from datetime import datetime

from hr.models import Leaves, Announcement, BankAccount

from django.views.generic import (
    DetailView,
    # ListView,
    # UpdateView,
    # DeleteView,
)

@login_required(login_url=reverse_lazy('employee:login'))
def index_view(request):
  return redirect('employee:home')


@login_required(login_url=reverse_lazy('employee:login'))
def home_view(request):

  now = datetime.date(datetime.now())
  annoucements = Announcement.objects.filter(start_date__lte = now, end_date__gte=now).order_by('-pk')
  leaves = Leaves.objects.get(user=request.user)
  
  context = {
    'theemp':request.user,
    'leaves' : leaves,
    'annoucements':annoucements
  }
  return render(request, 'employee/emp_home.html', context)


@method_decorator([login_required(login_url=reverse_lazy('employee:login'))], name='dispatch')
class PersonalDetailView(DetailView):
  model = User
  template_name = 'employee/emp_personal_detail.html'

  def get_context_data(self, **kwargs):
      context = super(PersonalDetailView, self).get_context_data(**kwargs)
      theuser = User.objects.get(pk=self.kwargs["pk"])
      bank = BankAccount.objects.get(user=theuser)

      context['theemp'] = theuser
      context['bank'] = bank

      return context


@method_decorator([login_required(login_url=reverse_lazy('employee:login'))], name='dispatch')
class CompanyDetailView(DetailView):
  model = User
  template_name = 'employee/emp_company_detail.html'

  def get_context_data(self, **kwargs):
      context = super(CompanyDetailView, self).get_context_data(**kwargs)
      theuser = User.objects.get(pk=self.kwargs["pk"])

      context['theemp'] = theuser

      return context


def emp_login_view(request):
  if request.method == 'POST':
    form = AuthenticationForm(data=request.POST)
    
    if form.is_valid():
      user = form.get_user()

      if user.is_active:
        login(request, user)
        
        if 'next' in request.POST:
          return redirect(request.POST.get('next'))
        else:
          return redirect('employee:home')
  else:
    form = AuthenticationForm()
  return render(request, 'employee/emp_login.html', {'form': form})


def emp_logout_view(request):
  logout(request)
  return redirect("employee:login")

employee/templates/employee/includes/_emp_col1.html
<div class="col l2 m6 s12">
  <div class="card" id="avatarcard">
    <div class="card-image">
      <img src="{{theemp.profile.avatar.url}}" alt="">
      <span class="z-depth-1 card-title empnum deep-orange accent-3">ID: {{theemp.profile.employee_id}}</span>
    </div>
    <div class="card-content center">
      <h6>
        {{theemp.first_name}} {{theemp.last_name}} 
      </h6>
      <p>{{theemp.profile.designation}}</p>
    </div>

  </div>

  <div class="card">
    <div class="card-content center joiningdate">
      <h6>Joining Date</h6>
      <h5 class="bold  light-green-text text-darken-3">{{theemp.profile.joining_date}}</h5>

    </div>
  </div>
</div>

employee/templates/employee/includes/_emp_header.html
{% load static %}
<header>
    <div class="navbar-fixed ">
        <nav class="cyan z-depth-1">
            <div class="nav-wrapper">
                <a href="" class="brandlogo valign-wrapper left">
                    <img src="{% static 'img/simplehrms-white2-cyan.jpg' %}">
                </a>
                <ul class="right hide-on-med-and-down push" id="top-navbar">
                    <li>
                        <!-- Dropdown Trigger -->
                        <a class='dropdown-trigger' href='#' data-target='dropdown-profile'>
                            <i class="material-icons">face</i>
                        </a>
                        <!-- Dropdown Structure -->
                        <ul id='dropdown-profile' class='dropdown-content'>
                            <li>
                                <a href="#" class="myavatar">
                                    <img src="{{request.user.profile.avatar.url}}" class="circle" height="45" width="45">
                                    <span class="right">{{request.user.username}}</span>
                                </a>
                            </li>
                            <li class="divider" tabindex="-1"></li>
                            <li class="logout-holder">
                                <div class="form-logout">
                                {% if user.is_authenticated %}
                                    <a href="{% url 'employee:logout' %}" class="btn-logoutemp left"><i class="material-icons left exit">exit_to_app</i> Logout</a>
                                {% endif %}
                                </div>
                            </li>
                            </ul>
                    </li>
                
                </ul>
            </div>
        </nav>
        
    </div>
</header>